// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://drzyqnwxgziwdrxafxtk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRyenlxbnd4Z3ppd2RyeGFmeHRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MTk5OTIsImV4cCI6MjA3MTE5NTk5Mn0.G6XCPGBF-BfPyizoCuP2TFE6MSR4xEPN3__eCnrlf_o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});