// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vhihjlqkwaywlszikivn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZoaWhqbHFrd2F5d2xzemlraXZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MDU1MjksImV4cCI6MjA3NDM4MTUyOX0.pNcP892JTLVrujlkIO2s5U_EKpuK7GCemr0MpzatHjc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});